service: ml-apps
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  ecr:
    images:
      ml-image:
        path: ./ml-inference/
  timeout: 300
  memorySize: 1000
  region: eu-west-3
  
# you can overwrite defaults here
#  stage: dev
resources:
 AWSTemplateFormatVersion: '2010-09-09'
 Transform: AWS::Serverless-2016-10-31
 Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ml-bucket-test-hm5
  EfsFileSystem:
    Type: AWS::EFS::FileSystem
  AccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref EfsFileSystem
      PosixUser:
        Gid: "1000"
        Uid: "1000"
      RootDirectory:
        Path: "/ml"
        CreationInfo:
          OwnerGid: "1000"
          OwnerUid: "1000"
          Permissions: "755"  
      
functions:
  apps3:
    handler: s3-efs/apps3.lambda_handler
    runtime: python3.8   
    events:
      - S3:
           bucket: ml-bucket-test-hm5
           event: s3:ObjectCreated:*
           
           rules: 
               - prefix: uploads/
               - suffix: .jpg
           existing: true
           forceDeploy: true


  appml:  
    image:
      name: ml-image 
    runtime: python3.8  
    events:  
       - httpApi:
          path: /
          method: get
