service: ml-apps
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  ecr:
    images:
      ml-image:
        path: ./ml-inference/
  timeout: 300
  memorySize: 1000
  region: eu-west-3
  
# you can overwrite defaults here
#  stage: dev
resources:
 AWSTemplateFormatVersion: '2010-09-09'
 Transform: AWS::Serverless-2016-10-31
 Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ml-bucket-test-hm5
  EfsFileSystem:
    Type: AWS::EFS::FileSystem
         
functions:
  app1:
    handler: s3-efs/app.lambda_handler
  app2:  
    image:
      name: ml-image 
      events:  
       - httpApi:
          method: POST
